export const images = [
  {
    src: "winteroutside2.jpg",
    original: `${process.env.PUBLIC_URL}/outside3.jpg`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside1.jpg",
    original: `${process.env.PUBLIC_URL}/outside3.jpg`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside3.jpg",
    original: `${process.env.PUBLIC_URL}/outside3.jpg`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside4.jpg",
    original: `${process.env.PUBLIC_URL}/outside3.jpg`,
    width: 1158,
    height: 980,
  }, 
  {
    src: "economyroom.jpg",
    original: `${process.env.PUBLIC_URL}/economyroom.jpg`,
    width: 4032,
    height: 3024,
  },
  {
    src: "food1.jpg",
    original: `${process.env.PUBLIC_URL}/food1.jpg`,
     width: 1158,
    height: 980,
  },
  {
    src: "hostelroom2.jpg",
    original: `${process.env.PUBLIC_URL}/hostelroom2.jpg`,
    width: 4032,
    height: 3024,
  },
  {
    src: "food2.jpg",
    original: `${process.env.PUBLIC_URL}/food2.jpg`,
     width: 1158,
    height: 980,
  },
  {
    src: "bedroom1.jpg",
    original: `${process.env.PUBLIC_URL}/bedroom1.jpg`,
    width: 4032,
    height: 3024,
  },
  {
    src: "hall2.jpg",
    original: `${process.env.PUBLIC_URL}/hall2.jpg`,
     width: 1158,
    height: 980,
  },
  {
    src: "outside2.jpg",
    original: `${process.env.PUBLIC_URL}/outside2.jpg`,
     width: 1158,
    height: 980,
  },
  {
    src: "hall.jpg",
    original: `${process.env.PUBLIC_URL}/hall.jpg`,
     width: 1158,
    height: 980,
  },
  {
    src: "hall3.jpg",
    original: `${process.env.PUBLIC_URL}/hall3.jpg`,
     width: 1158,
    height: 980,
  },
  {
    src: "outside3.jpg",
    original: `${process.env.PUBLIC_URL}/outside3.jpg`,
     width: 1158,
    height: 980,
  },
  {
    src: "hostelroom.jpg",
    original: `${process.env.PUBLIC_URL}/hostelroom.jpg`,
    width: 4032,
    height:3024 ,
  },
  {
    src: "guests1.jpg",
    original: `${process.env.PUBLIC_URL}/guests1.jpg`,
     width: 1158,
    height: 980,
  },
  {
    src: "hall4.jpg",
    original: `${process.env.PUBLIC_URL}/hall4.jpg`,
    width: 1158,
    height: 980,
  },
  
  {
    src: "night.jpg",
    original: `${process.env.PUBLIC_URL}/night.jpg`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside5.jpg",
    original: `${process.env.PUBLIC_URL}/outside3.jpg`,
    width: 1158,
    height: 980,
  },
  {
    src: "winteroutside6.jpg",
    original: `${process.env.PUBLIC_URL}/outside3.jpg`,
    width: 1158,
    height: 980,
  },
]
